version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./public/html:/var/www/html
      - ./nginx/conf:/etc/nginx/conf/
    restart: always
    ports:
      - "80:80"
    container_name: nginx_html